data_product_id: derived
data_product_name: ""
data_product_type: ""
data_product_description: "" 
data_product_icon: ""
data_product_category: ""
data_product_geo_region: ""
data_product_owner: ""
data_product_documentation: ""
domain: ""
domain_owner: ""
domain_type: "" 
last_modified_by: ""
last_modify_date: ""
